# Generated by Django 4.1.6 on 2023-08-28 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appresult', '0001_initial'),
        ('appsearch', '0001_initial'),
        ('appaccount', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='user_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='user_pw',
            new_name='password',
        ),
    ]
