# Generated by Django 4.1.6 on 2023-09-18 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appaccount', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
