# Generated by Django 4.1.6 on 2023-08-31 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appaccount', '0002_rename_user_users_rename_user_id_users_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
