# Generated by Django 4.1.6 on 2023-08-31 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appresult', '0002_alter_mytimetable_user_id'),
        ('appaccount', '0003_user'),
        ('appsearch', '0002_alter_userbasket_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
