# Generated by Django 4.1.6 on 2023-08-08 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('lecture_id', models.IntegerField(primary_key=True, serialize=False)),
                ('lecture_curriculum', models.CharField(max_length=10)),
                ('lecture_classification', models.CharField(blank=True, max_length=15, null=True)),
                ('lecture_code', models.CharField(max_length=8)),
                ('lecture_number', models.CharField(max_length=5)),
                ('lecture_name', models.CharField(max_length=50)),
                ('lecture_professor', models.CharField(blank=True, max_length=10, null=True)),
                ('lecture_campus', models.CharField(blank=True, max_length=5, null=True)),
                ('lecture_credit', models.IntegerField()),
                ('lecture_univ', models.CharField(max_length=15)),
                ('lecture_major', models.CharField(max_length=25)),
                ('lecture_remark', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='lecture',
            constraint=models.UniqueConstraint(fields=('lecture_code', 'lecture_number'), name='unique_lecture'),
        ),
    ]
