# Generated by Django 4.1.6 on 2023-08-08 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_day', models.CharField(max_length=4)),
                ('lecture_start_time', models.FloatField(blank=True, null=True)),
                ('lecture_end_time', models.FloatField(blank=True, null=True)),
                ('lecture_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.lecture')),
            ],
        ),
        migrations.CreateModel(
            name='LectureRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_room', models.CharField(max_length=30)),
                ('lecture_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.lecture')),
            ],
        ),
    ]
