# Generated by Django 4.1.6 on 2023-08-31 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appaccount', '0003_user'),
        ('appresult', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytimetable',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appaccount.user'),
        ),
    ]
